# Generated by Django 5.2.4 on 2025-09-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_gender_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='app_elec',
            new_name='APP_ELEC',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='app_meca',
            new_name='APP_MECA',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='cdq',
            new_name='CDQ',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='cro1',
            new_name='CRO1',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='cro2',
            new_name='CRO2',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='laboratin1',
            new_name='Laboratin1',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='laboratin2',
            new_name='Laboratin2',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='patroller1',
            new_name='Patroller1',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='patroller2',
            new_name='Patroller2',
        ),
    ]
