# Generated by Django 5.2.4 on 2025-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_app_elec_shift_app_elec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_production',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='compteur_debut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='compteur_fin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='dechargement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='duree',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='ensilage_silo',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='port_production',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port_production',
            name='situation_entree_quart',
            field=models.CharField(blank=True, choices=[('En Marche', 'En Marche'), ('En Arret', 'En Arret')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
