# Generated by Django 5.2.4 on 2025-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_port_production_commentaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dryer_production',
            name='PZ_humide_Production',
        ),
        migrations.RemoveField(
            model_name='dryer_production',
            name='bande_melange_Production',
        ),
        migrations.RemoveField(
            model_name='dryer_production',
            name='compteur_horaire_Production',
        ),
        migrations.AddField(
            model_name='dryer_production',
            name='ensilage_silo',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dryer_production',
            name='quality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dryer_production',
            name='situation_entree_quart',
            field=models.CharField(blank=True, choices=[('En Marche', 'En Marche'), ('En Arret', 'En Arret')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dryer_production',
            name='humidites_entree',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dryer_production',
            name='humidites_sortie',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dryer_production',
            name='production',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
