# Generated by Django 5.2.4 on 2025-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_dryer_production_pz_humide_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryer_production',
            name='ensilage_silo',
            field=models.TextField(default=dict),
        ),
    ]
