# Generated by Django 5.2.4 on 2025-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_dryer_production_ensilage_silo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryer_production',
            name='ensilage_silo',
            field=models.CharField(default=dict),
        ),
    ]
