# Generated by Django 5.2.4 on 2025-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_dryer_production_ensilage_silo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_production',
            name='ensilage_silo',
            field=models.CharField(default=dict),
        ),
    ]
