# Generated by Django 5.2.4 on 2025-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_port_production_ensilage_silo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mill_production',
            name='compteur_horaire_Production',
        ),
        migrations.RemoveField(
            model_name='mill_production',
            name='situation_entree_quart',
        ),
        migrations.AddField(
            model_name='mill_production',
            name='clinker_Difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='compteur_horaire_Difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='fine_Difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='gypse_Difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='no_godets_receptions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='pouzzolane_Difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mill_production',
            name='ensilage_silo',
            field=models.CharField(default=dict),
        ),
        migrations.AlterField(
            model_name='mill_production',
            name='extraction_silo',
            field=models.CharField(default=dict),
        ),
        migrations.AlterField(
            model_name='mill_production',
            name='production',
            field=models.FloatField(),
        ),
    ]
