# Generated by Django 5.2.4 on 2025-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_mill_production_compteur_horaire_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill_production',
            name='production',
            field=models.IntegerField(),
        ),
    ]
