# Generated by Django 5.2.4 on 2025-09-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_mill_production_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mill_production',
            name='ciment_id',
        ),
        migrations.RemoveField(
            model_name='mill_production',
            name='equipement_id',
        ),
    ]
