# Generated by Django 5.2.4 on 2025-09-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_employee_id_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='operatorType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability', models.IntegerField(blank=True, null=True)),
                ('optimization', models.IntegerField(blank=True, null=True)),
                ('environment', models.IntegerField(blank=True, null=True)),
                ('production', models.IntegerField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Performance', to='authentication.shift')),
            ],
        ),
    ]
