# Generated by Django 5.2.4 on 2025-10-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_feedback_operatortype_mill_production_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill_production',
            name='arret_par_incident',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
