# Generated by Django 5.2.4 on 2025-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_mill_production_arret_par_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill_production',
            name='Ecart_type',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mill_production',
            name='HNA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
