# Generated by Django 5.2.4 on 2025-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_mill_production_ecart_type_mill_production_hna'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill_production',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
